name: Project ENV Vars
author: Ryan Couse
description: Create Project ENVs based on convention from git branch ref.
runs:
    using: node12
    main: 'main.js'
branding:
    icon: upload
    color: orange
